Additional frontend styles for NMA repository
EOSC-CZ/nma pull request #6
Opened 2024-06-14 07:14 UTC by corovcam

2024-06-14 07:58 UTC, mirekys commented on .pdm-python
This file shouldn't be in git

2024-06-24 08:48 UTC, mirekys requested changes

2024-06-24 08:48 UTC, mirekys commented on ui/datasets/semantic-ui/js/datasets/citations/components/RecordCitations.jsx
> +const CITATION_STYLES = [
These 2 constants need to come from backend config (what styles are supported there can change)

2024-06-24 13:23 UTC, corovcam commented on ui/datasets/semantic-ui/js/datasets/citations/components/RecordCitations.jsx
> +const CITATION_STYLES = [
Sure, that's why these are passed as a prop (so it'll be extendible when we'll have common backend for citations).

2024-06-24 15:40 UTC, mirekys commented on common/datasets/serializers/citations/csl/schema.py
> +    def _read_resource_type(self, id_):
Is this method used somewhere?

2024-06-24 15:42 UTC, mirekys commented on ui/datasets/semantic-ui/js/datasets/citations/components/RecordCitations.jsx
> +const CITATION_STYLES = [
OK, we'll solve as part of common backend integration/implementation in a different issue :)

2024-06-25 11:06 UTC, mirekys commented on ui/datasets/semantic-ui/js/datasets/citations/components/CitationField.jsx
> +    return `<a href="${url}" target="_blank">${url}</a>${trailingDot}`;
rel="noopener, noreferrer" should be added for link security

2024-06-26 07:36 UTC, mirekys commented on ui/datasets/semantic-ui/templates/datasets/search/PaginationElement.jsx
why https://inveniosoftware.github.io/react-searchkit/docs/components/pagination isn't used here?

2024-06-26 07:39 UTC, mirekys commented on ui/datasets/semantic-ui/templates/datasets/search/ResultsPerPageElement.jsx
Why not https://inveniosoftware.github.io/react-searchkit/docs/components/results-per-page?

2024-06-26 10:12 UTC, corovcam commented on common/datasets/serializers/citations/csl/schema.py
> +    def _read_resource_type(self, id_):
Yes, some of these methods are copied (some slightly changed from UCT Repository. 

e.g.: https://github.com/VSCHT/uct-repository/blob/15113d1bbbb8963d9b577f221dcbf3803f89b707/common/theses/serializers/citations/csl/schema.py#L52

2024-06-26 11:22 UTC, mirekys approved these changes

2024-06-26 11:27 UTC, corovcam commented on ui/datasets/semantic-ui/templates/datasets/search/PaginationElement.jsx
Because I needed to add extra props, i.e. `color: teal, text: true`, and this was the only way. `parametrize` unfortunately doesn't work here and creates an endless overriding loop for some reason.

2024-06-26 11:31 UTC, mirekys approved these changes

2024-06-26 11:32 UTC, corovcam commented on ui/datasets/semantic-ui/templates/datasets/search/ResultsPerPageElement.jsx
Similar to PagimationElement, I needed to add `compact, selection, className` props.

2024-06-26 11:50 UTC, merged